queue_rules:
  - name: default
    conditions: []

pull_request_rules:
  - name: assign PR to the author
    conditions:
      - "#assignee=0"
    actions:
      assign:
        users: ["{{author}}"]

  - name: squash-merge PRs labelled as ready
    conditions:
      - "label=ready to merge"
    actions:
      queue:
        method: merge
        name: default
        
  - name: merge-update PRs labelled to be kept up to date
    conditions:
      - "label=keep up to date"
    actions:
      update: {}

  - name: remove automation labels on merged PRs
    conditions:
      - merged
    actions:
      label:
        remove:
          - "ready to merge"
          - "keep up to date"
