name: greetings

on: [issues, pull_request]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      continue-on-error: true
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          Hey! Thanks for adding an issue, please @ one of our team
          members so that we can figure this out as fast as we can.
        pr-message: |
          Hey!

          It seems it's your first time opening up a PR in DGX, That's superb!

          Please give our [Contributing Practices](https://github.com/Tapad/dgx/blob/master/docs/markdowns/contributing.md)
          a look before continuing, it should contain all information you need.

          Don't hesitate to assign this PR to other people and ask them for help as well.

          We are a helpful bunch ;)
