name: Release

on:
  workflow_run:
    workflows: [ci]
    types: [completed]
    branches: [master]

  workflow_dispatch:
    inputs:
      actor:
        description: "The login of the user that initiated the deployment"
        required: false
        default: ""
      comment-id:
        description: 'The comment-id of the slash command'
        required: false

concurrency: deployment-${{ github.ref }}

jobs:
  version-prep:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.auto-version.outputs.version }}
      DOCKER_ID: ${{ steps.artifact-variables.outputs.DOCKER_ID }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: Tapad/gha-auto-release@v0
        name: Calculate version
        id: auto-version

  build-package:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: [version-prep]
    if: ${{ needs.version-prep.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Remove all previous built packages
        run: rm -rf dist/

      - name: Use build virtualenv
        uses: Tapad/gha-python-env@v0
        with:
          requirement_files: requirements/tasks.build.txt
          python_version: 3.8

      - name: Create version file
        run: |
          echo -n "${{ needs.version-prep.outputs.VERSION }}" > airflow_common/VERSION

      - name: Build python package wheel
        run: python3 -m build --wheel

      - name: Nexus wheel upload
        run: |
          python3 -m twine check dist/*.whl
          python3 -m twine upload \
            --repository-url "https://nexus.tapad.com/repository/pypi-local/" \
            -u github-actions -p ${{ secrets.NEXUS_PASS_FOR_GITHUB_ACTIONS }} \
            --skip-existing --non-interactive --disable-progress-bar --verbose \
            dist/*.whl




  update-comment:
    if: ${{ github.event.inputs.comment-id }}
    runs-on: ubuntu-latest
    steps:
      - name: update comment with url
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ github.event.inputs.comment-id }}
          body: >
            > ${{ github.workflow }} workflow :running::dash: 
            [check status](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})